import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const mode = process.argv[2];
const prod = mode === "production" || mode === "production-lite";
// Lite build (community-store artifact): the OAuth gate is tree-shaken out
// entirely — express and the SDK auth router never enter main.js.
// PLN — MCP OAuth Shim, D6.
const includeOAuth = mode !== "production-lite";

// The MCP SDK imports builtins via the "node:" prefix; mark them external and
// strip the prefix so the bundle emits require("crypto") etc., which Obsidian's
// runtime require resolves on desktop.
const nodePrefixExternal = {
	name: "node-prefix-external",
	setup(build) {
		build.onResolve({ filter: /^node:/ }, (args) => ({
			path: args.path.slice("node:".length),
			external: true,
		}));
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["plugin/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins],
	plugins: [nodePrefixExternal],
	define: {
		BUILD_OAUTH: JSON.stringify(includeOAuth),
	},
	// Embed skill files as strings so the plugin can write them to disk for the
	// user (plugin/skills-bundle.ts + Settings → Agent skills).
	loader: {
		".md": "text",
		".yml": "text",
		".sh": "text",
	},
	format: "cjs",
	// es2020: the OAuth gate's dependency tree contains BigInt literals
	// (es2018-incompatible); Obsidian 1.5+ Electron handles es2020 fine.
	target: "es2020",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
